version: 2.1

jobs:
  build-linux-x86:
    resource_class:
      large
    docker:
      - image: cimg/rust:1.70
    steps:
      - checkout
      - run:
          name: Print versions
          command: rustc --version; rustup --version; ~/.cargo/bin/cargo --version
      - run:
          name: Generate lockfile
          command: ~/.cargo/bin/cargo generate-lockfile
      - restore_cache:
          name: Restore cache
          keys:
            - cargo-v0-linux-{{ arch }}-{{ checksum "Cargo.lock" }}
            - cargo-v0-linux-{{ arch }}
      - run:
          name: Build debug
          command: ~/.cargo/bin/cargo build
      - run:
          name: Run tests
          command: ~/.cargo/bin/cargo test --verbose --no-fail-fast
      - run:
          name: Build release
          command: ~/.cargo/bin/cargo build --release
      - run:
          name: Run benchmarks
          command: ~/.cargo/bin/cargo bench
      - run:
          name: Run linter
          command: ~/.cargo/bin/cargo clippy
      - run:
          name: Run format check
          command: ~/.cargo/bin/cargo fmt --check
      - run:
          name: Build docs
          command: RUSTDOCFLAGS="--html-in-header .cargo/header.html" ~/.cargo/bin/cargo doc --no-deps
      - save_cache:
          name: Save cache
          key: cargo-v0-linux-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
            - target/.rustdoc_fingerprint.json
            - target/doc
            - tests/assets/hg38.p13.2bit

  build-macos-x86:
    resource_class:
      macos.x86.medium.gen2
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: Print versions
          command: rustc --version; rustup --version; ~/.cargo/bin/cargo --version
      - run:
          name: Generate lockfile
          command: ~/.cargo/bin/cargo generate-lockfile
      - restore_cache:
          name: Restore cache
          keys:
            - cargo-v0-macos-{{ arch }}-{{ checksum "Cargo.lock" }}
            - cargo-v0-macos-{{ arch }}
      - run:
          name: Download rustup
          command: curl -o rustup https://sh.rustup.rs
      - run:
          name: Install rust
          command: bash rustup -y
      - run:
          name: Build debug
          command: ~/.cargo/bin/cargo build
      - run:
          name: Run tests
          command: ~/.cargo/bin/cargo test --verbose --no-fail-fast
      - run:
          name: Build release
          command: ~/.cargo/bin/cargo build --release
      - run:
          name: Run benchmarks
          command: ~/.cargo/bin/cargo bench
      - run:
          name: Run linter
          command: ~/.cargo/bin/cargo clippy
      - run:
          name: Run format check
          command: ~/.cargo/bin/cargo fmt --check
      - run:
          name: Build docs
          command: RUSTDOCFLAGS="--html-in-header .cargo/header.html" ~/.cargo/bin/cargo doc --no-deps
      - save_cache:
          name: Save cache
          key: cargo-v0-macos-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
            - target/.rustdoc_fingerprint.json
            - target/doc
            - tests/assets/hg38.p13.2bit

workflows:
  build-all:
    jobs:
      - build-linux-x86
      - build-macos-x86
