version: 2.1

jobs:
  build_test_bench:
    docker:
      - image: cimg/rust:1.70
    steps:
      - checkout
      - run: "cargo build"
      - run: "cargo test"
      - run: "cargo build --release"
      - run: "cargo bench"

workflows:
  main:
    jobs:
      - build_test_bench
