version: 2.1

jobs:
  build-test-bench:
    docker:
      - image: cimg/rust:1.70
    steps:
      - checkout
      - run:
          name: Print versions
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Generate lockfile
          command: cargo generate-lockfile
      - restore_cache:
          name: Restore cache
          key: cargo-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build debug
          command: cargo build
      - run:
          name: Run tests
          command: cargo test
      - run:
          name: Build release
          command: cargo build --release
      - run:
          name: Run benchmarks
          command: cargo bench
      - run:
          name: Install linter and format checker
          command: rustup component add clippy; rustup component add rustfmt
      - run:
          name: Run lint
          command: cargo clippy
      - run:
          name: Check formatting
          command: cargo fmt --check
      - run:
          name: Generate docs
          command: cargo doc; RUSTDOCFLAGS="--html-in-header .cargo/header.html" cargo doc --no-deps
      - save_cache:
          name: Save cache
          key: cargo-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
            - target/.rustdoc_fingerprint.json
            - target/doc

workflows:
  build-test-bench-workflow:
    jobs:
      - build-test-bench
